### ISSUE TITLE
Error while running it

### ISSUE THREAD

**Issue by miguelpoyatosmora** [dohsimpson/kubernetes-doc-pdf#4]
```
C:\workspace\github\dohsimpson\kubernetes-doc-pdf>pip install pipenv
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl (5.2MB)
    100% |████████████████████████████████| 5.2MB 1.6MB/s
Requirement already satisfied: pip>=9.0.1 in c:\users\poyatm01\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (19.0.3)
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 163kB 1.4MB/s
Collecting virtualenv (from pipenv)
  Downloading https://files.pythonhosted.org/packages/8b/12/8d4f45b8962b03ac9efefe5ed5053f6b29334d83e438b4fe379d21c0cb8e/virtualenv-16.7.5-py2.py3-none-any.whl (3.3MB)
    100% |████████████████████████████████| 3.3MB 1.1MB/s
Requirement already satisfied: setuptools>=36.2.1 in c:\users\poyatm01\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (40.8.0)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/ba/f8/50c2b7dbc99e05fce5e5b9d9a31f37c988c99acd4e8dedd720b7b8d4011d/virtualenv_clone-0.5.3-py2.py3-none-any.whl
Installing collected packages: certifi, virtualenv, virtualenv-clone, pipenv
Successfully installed certifi-2019.6.16 pipenv-2018.11.26 virtualenv-16.7.5 virtualenv-clone-0.5.3
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\workspace\github\dohsimpson\kubernetes-doc-pdf>pipenv install
Creating a virtualenv for this project…
Pipfile: C:\workspace\github\dohsimpson\kubernetes-doc-pdf\Pipfile
Using C:/Users/Poyatm01/AppData/Local/Programs/Python/Python37-32/python.exe (3.7.3) to create virtualenv…
[=   ] Creating virtual environment...Already using interpreter C:\Users\Poyatm01\AppData\Local\Programs\Python\Python37-32\python.exe
Using base prefix 'C:\\Users\\Poyatm01\\AppData\\Local\\Programs\\Python\\Python37-32'
New python executable in C:\Users\Poyatm01\.virtualenvs\kubernetes-doc-pdf-f5LapLRh\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:/Users/Poyatm01/AppData/Local/Programs/Python/Python37-32/python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\Poyatm01\.virtualenvs\kubernetes-doc-pdf-f5LapLRh
Installing dependencies from Pipfile.lock (c42e03)…
  ================================ 22/22 - 00:00:19
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

C:\workspace\github\dohsimpson\kubernetes-doc-pdf>pipenv shell
Launching subshell in virtual environment…
Microsoft Windows [Version 10.0.16299.1331]
(c) 2017 Microsoft Corporation. All rights reserved.

(kubernetes-doc-pdf-f5LapLRh) C:\workspace\github\dohsimpson\kubernetes-doc-pdf>python kubernetes-doc.py
Setup
downloading...
Traceback (most recent call last):
  File "kubernetes-doc.py", line 63, in <module>
    generate_directory_pdf(url, name)
  File "kubernetes-doc.py", line 39, in generate_directory_pdf
    f.write(html)
  File "C:\Users\Poyatm01\.virtualenvs\kubernetes-doc-pdf-f5LapLRh\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 5290: character maps to <undefined>


```

**Comment by dohsimpson** [comment]
Could be the default codecs on your PC, try https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters
